### ISSUE TITLE
Demonizer le service

### ISSUE THREAD

**Issue by Riz-cros** [raven-os/albinos#142]
Il faut demonizer le service plutot que de le lancer a la main a chaque fois

**Comment by Gaspard--** [comment]
@Riz-cros done?

**Comment by Riz-cros** [comment]
Noupe

**Comment by Riz-cros** [comment]
On peut faire mieux et plu propre, en forkant nous meme le process et surtout en fermant nous meme stdin stdout et stderr et en ouvrant des logs

**Comment by Riz-cros** [comment]
mais pour ca il faut changer de logger et repenser tous les logs du services (qui sont pas ouf)

**Comment by Gaspard--** [comment]
`sed` pourrait pas aider à résoudre ça?

**Comment by Riz-cros** [comment]
heuuu je suis pas sur aue tu ai compris, faut que dans le code on change de lib de logger, de toute facons nos logs sont pas ouf et faut les refaire
