### ISSUE TITLE
Configuration storage

### ISSUE THREAD

**Issue by matthiasrigaud** [raven-os/albinos#20]
Define an architecture for DB, integrate DB to project, implement functions relative to DB

**Comment by Riz-cros** [comment]
Database is almost ready to be integrated to the service, most of it can already be integrated (create/delete config, set/delete setting).

I'm not sure about the load_config in the protocol ? should it ask for the database to fetch all settings of a the specified config and return them ?

Need more work on the views, its seems doable but rather complicated, merging multiple tables between them is possible with statement such as `union` or `join`. however the tricky part is to select for each row, a column either from one table or another upon some conditions, so I need to find an answer for that.

**Comment by matthiasrigaud** [comment]
@Riz-cros I think it's not important to think to "load_config" now, and I'm not sure you'll have to do something during the configuration loading anyway. This request is made for the library, to allow it to inform the service of its presence, and to specify the key and the type of "connection" (RO/RW).

**Comment by Riz-cros** [comment]
Remettre au propre la DB

**Comment by Riz-cros** [comment]
Cacher le load des configs
