### ISSUE TITLE
Doumentation generation

### ISSUE THREAD

**Issue by Gaspard--** [raven-os/albinos#6]
While markdown can help understanding the philosophy, the API would be better understood with a proper documentation.
Doxygen should be set up just like for claws.

**Comment by Milerius** [comment]
I'm disagree with generated documentation usually because they are most of the time unreadable can we look into Modern free solution such as https://www.gitbook.com/?t=1 or https://squidfunk.github.io/mkdocs-material/

**Comment by Gaspard--** [comment]
I'm okay with a hand written document, but those tend to go out of date pretty fast. We should probably have both.

**Comment by Milerius** [comment]
I'm ok for both
