### ISSUE TITLE
Re-think config inclusion

### ISSUE THREAD

**Issue by Gaspard--** [raven-os/albinos#65]
Current version doesn't seem very usable because:
- we have an order sensitive inclusion, which doesn't seem to be easy to manipulate from the API
- we have no way of "un-including" a config
The api definition of config inclusion is also broken (3 parameters, while 2 are needed)

**Comment by matthiasrigaud** [comment]
I think this issue was resolved with the last PR for the API.  @Gaspard--

**Comment by Gaspard--** [comment]
Indeed, done in #77
