### ISSUE TITLE
Client config_id abstraction

### ISSUE THREAD

**Issue by Gaspard--** [raven-os/albinos#76]
Currently the client gets th id from for the db. There are no permission checks and clients could potentially guess ids.
Ideally we need a per-client hashmap that maps a client config_id to the corresponding db config_id and information about it's permissions to the config (readonly / readwrite).

**Comment by Gaspard--** [comment]
This also adresses #49

**Comment by Gaspard--** [comment]
see #87

**Comment by Riz-cros** [comment]
this also adresses #89
