### ISSUE TITLE
Find a way to lookup temporary ids given a config db id

### ISSUE THREAD

**Issue by Riz-cros** [raven-os/albinos#89]

**Comment by Riz-cros** [comment]
The idea is given a list of client, find for each all the temporary id coresponding to a config db id

**Comment by Riz-cros** [comment]
Needed in order to complete #90

**Comment by Gaspard--** [comment]
I'm not sure, don't you miss the reverse mapping ?

**Comment by Riz-cros** [comment]
yeah thats why I opened this issue
